apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-mass
  app: massmutual
spec:
  template:
    metadata:
      app: massmutual
    spec:
      containers:
      - name: app
        image: mahijs/dell-app:latest
        ports:
        - containerPort: 80
  replicas: 3
  selector:
    matchLabels:
      app: massmutual
